# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1cd32406769436f8cef10c6e838f9fa9cd464276fdcd6587a521637412402dffe114349640daec94d20ec9b192abbca46e21e200c02640ce0489399a18a189f

test:
  secret_key_base: 2c35c8c0781a5166caebeca73fa8271ff58625e7542e44224fa60b5b1bf4274d8916d18afb46cc0ce2222610a1009f3178bc08d6bf9747cac02ead79885d8ddc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
